'use client';

import { useState } from 'react';

export type MarketSource = { title: string; url: string; note: string };
export type Service = {
  id: string; name: string; description: string; scope: string; conditions: string; category: string; unit: string; price: number;
  marketMinPrice: number|null; marketMaxPrice: number|null; marketRationale: string; marketSources: MarketSource[]; marketCheckedAt: string|null; taxExempt: boolean; active: boolean;
};
const money = (value: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(value || 0);
const blank = (): Omit<Service,'id'> => ({ name:'',description:'',scope:'',conditions:'',category:'Servicios técnicos',unit:'servicio',price:0,marketMinPrice:null,marketMaxPrice:null,marketRationale:'',marketSources:[],marketCheckedAt:null,taxExempt:false,active:true });

export function ServicesPanel({ services, onSave, onDelete }: { services: Service[]; onSave: (service: Omit<Service,'id'>, id?: string) => Promise<void>; onDelete: (service: Service) => Promise<void> }) {
  const [editing, setEditing] = useState<Service|null>(null), [createOpen, setCreateOpen] = useState(false);
  return <><div className="page-heading"><div><div className="eyebrow">MANO DE OBRA Y SERVICIOS TÉCNICOS</div><h1>Catálogo de servicios</h1><p>Servicios cotizables separados de los equipos y productos.</p></div><button className="button primary" onClick={() => setCreateOpen(true)}>＋ Crear servicio con IA</button></div>
    <div className="service-tax-note"><b>Tratamiento tributario configurable</b><span>Los servicios se crean afectos a IVA por defecto. Marca una línea exenta/no afecta solo cuando corresponda a tu situación tributaria.</span></div>
    <div className="service-grid">{services.map(service=><article className={`service-card ${!service.active?'inactive':''}`} key={service.id}><div className="catalog-card-top"><span className="category-tag">{service.category}</span><div className="row-actions"><button onClick={() => setEditing(service)}>Editar</button><button className="danger-text" onClick={() => void onDelete(service)}>Eliminar</button></div></div><h3>{service.name}</h3><p>{service.description}</p><div className="service-price-row"><b>{money(service.price)}</b><span>/ {service.unit} · {service.taxExempt?'Exento/no afecto':'Afecto a IVA'}</span></div>{service.marketMinPrice!==null&&service.marketMaxPrice!==null&&<div className="service-market-range">Rango de mercado: {money(service.marketMinPrice)} – {money(service.marketMaxPrice)}{service.marketCheckedAt&&<small>Consultado el {new Intl.DateTimeFormat('es-CL').format(new Date(service.marketCheckedAt))}</small>}</div>}<details><summary>Alcance y condiciones</summary><p><b>Incluye:</b> {service.scope||'Sin especificar'}</p><p><b>Condiciones:</b> {service.conditions||'Sin especificar'}</p></details>{service.marketSources.length>0&&<div className="service-source-list">{service.marketSources.map((source,index)=><a key={`${source.url}-${index}`} href={source.url} target="_blank" rel="noreferrer">Referencia {index+1} ↗</a>)}</div>}</article>)}{services.length===0&&<div className="catalog-empty"><b>El catálogo está vacío</b><span>Crea servicios manualmente o solicita a la IA una investigación de mercado.</span></div>}</div>
    {(createOpen||editing)&&<ServiceEditor key={editing?.id||'new'} initial={editing} onClose={() => { setCreateOpen(false); setEditing(null); }} onSave={async value=>{await onSave(value,editing?.id);setCreateOpen(false);setEditing(null)}}/>}
  </>;
}

function ServiceEditor({ initial, onClose, onSave }: { initial: Service|null; onClose: () => void; onSave: (service: Omit<Service,'id'>) => Promise<void> }) {
  const [service,setService]=useState<Omit<Service,'id'>>(initial?{...initial}:blank()),[saving,setSaving]=useState(false),[researching,setResearching]=useState(false),[error,setError]=useState('');
  const set=<K extends keyof Omit<Service,'id'>>(key:K,value:Omit<Service,'id'>[K])=>setService(current=>({...current,[key]:value}));
  async function research(){if(service.name.trim().length<3){setError('Escribe el nombre del servicio antes de investigar.');return}setResearching(true);setError('');try{const response=await fetch('/api/services/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:service.name,category:service.category,details:service.description})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo completar la investigación.');setService(current=>({...current,name:data.name,description:data.description,scope:data.scope,conditions:data.conditions,category:data.category,unit:data.unit,price:data.recommendedPrice,marketMinPrice:data.minPrice,marketMaxPrice:data.maxPrice,marketRationale:data.rationale,marketSources:data.marketSources,marketCheckedAt:data.marketCheckedAt}));}catch(e){setError(e instanceof Error?e.message:'No se pudo investigar el servicio.')}finally{setResearching(false)}}
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setError('');try{await onSave(service)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el servicio.')}finally{setSaving(false)}}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="modal wide service-editor" role="dialog" aria-modal="true" aria-labelledby="service-editor-title"><header className="modal-head"><div><h2 id="service-editor-title">{initial?'Editar servicio':'Crear servicio'}</h2><p>Define alcance, precio neto, condiciones y tratamiento de IVA.</p></div><button type="button" className="modal-close" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="modal-body service-editor-body">
    <div className="service-ai-box"><div><b>Investigación de mercado en vivo</b><span>La IA buscará referencias chilenas para sugerir alcance, condiciones y un rango de precios CLP.</span></div><button type="button" className="button outline" disabled={researching||!service.name.trim()} onClick={()=>void research()}>{researching?'Buscando referencias…':'✦ Investigar con IA'}</button></div>
    <div className="form-grid"><label className="field span2">Nombre del servicio<input required maxLength={180} value={service.name} onChange={event=>set('name',event.target.value)}/></label><label className="field">Categoría<input required maxLength={80} value={service.category} onChange={event=>set('category',event.target.value)}/></label><label className="field">Unidad de cobro<input maxLength={30} value={service.unit} onChange={event=>set('unit',event.target.value)} placeholder="servicio, hora, punto"/></label><label className="field span2">Descripción<textarea maxLength={1000} rows={2} value={service.description} onChange={event=>set('description',event.target.value)}/></label><label className="field span2">Alcance incluido<textarea maxLength={3000} rows={3} value={service.scope} onChange={event=>set('scope',event.target.value)}/></label><label className="field span2">Condiciones, exclusiones y supuestos<textarea maxLength={3000} rows={3} value={service.conditions} onChange={event=>set('conditions',event.target.value)}/></label><label className="field">Precio de venta neto CLP<input type="number" required min="0" max="2000000000" value={service.price} onChange={event=>set('price',Number(event.target.value))}/><small>El total de la cotización aplicará IVA si corresponde.</small></label><label className="field">Rango de referencia CLP<input type="text" readOnly value={service.marketMinPrice!==null&&service.marketMaxPrice!==null?`${money(service.marketMinPrice)} – ${money(service.marketMaxPrice)}`:'Sin investigar'} /></label>
    </div><label className="service-tax-option"><input type="checkbox" checked={service.taxExempt} onChange={event=>set('taxExempt',event.target.checked)}/><span><b>Marcar como exento/no afecto a IVA</b><small>Selecciona solo si la operación cumple los requisitos tributarios aplicables. La mano de obra no queda exenta automáticamente.</small></span></label>
    {service.marketRationale&&<div className="service-rationale"><b>Fundamento de mercado</b><p>{service.marketRationale}</p>{service.marketSources.map((source,index)=><a key={`${source.url}-${index}`} href={source.url} target="_blank" rel="noreferrer">{source.title||source.url} ↗</a>)}{service.marketCheckedAt&&<small>Consulta en vivo: {new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(service.marketCheckedAt))}</small>}</div>}
    <label className="field checkbox-field"><input type="checkbox" checked={service.active} onChange={event=>set('active',event.target.checked)}/> Disponible al cotizar</label>{error&&<div className="error-box" role="alert">{error}</div>}
  </div><footer className="modal-foot"><span>La investigación es una sugerencia; revisa y ajusta el precio.</span><div><button className="button outline" type="button" onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving||!service.name.trim()}>{saving?'Guardando…':'Guardar servicio'}</button></div></footer></form></section></div>;
}
